
interface _GlobalComponents {
      'UiActorCol': typeof import("../components/ui/actorCol/ActorCol.vue")['default']
    'UiBtnPrimary': typeof import("../components/ui/btnPrimary/BtnPrimary.vue")['default']
    'UiBtnSecondary': typeof import("../components/ui/btnSecondary/BtnSecondary.vue")['default']
    'UiHeader': typeof import("../components/ui/header/Header.vue")['default']
    'UiLoader': typeof import("../components/ui/loader/Loader.vue")['default']
    'UiPlatformCircle': typeof import("../components/ui/platformCircle/PlatformCircle.vue")['default']
    'UiPlatformTag': typeof import("../components/ui/platformTag/PlatformTag.vue")['default']
    'UiPlatformsList': typeof import("../components/ui/platformsList/PlatformsList.vue")['default']
    'UiPosterCard': typeof import("../components/ui/posterCard/PosterCard.vue")['default']
    'UiPostersList': typeof import("../components/ui/postersList/PostersList.vue")['default']
    'UiSearchBar': typeof import("../components/ui/searchBar/SearchBar.vue")['default']
    'UiSlider': typeof import("../components/ui/slider/Slider.vue")['default']
    'UiTag': typeof import("../components/ui/tag/Tag.vue")['default']
    'UiTrailersList': typeof import("../components/ui/trailersList/TrailersList.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'VueCarousel': typeof import("vue3-carousel/dist/carousel")['Carousel']
    'VueSlide': typeof import("vue3-carousel/dist/carousel")['Slide']
    'VuePagination': typeof import("vue3-carousel/dist/carousel")['Pagination']
    'VueNavigation': typeof import("vue3-carousel/dist/carousel")['Navigation']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyUiActorCol': typeof import("../components/ui/actorCol/ActorCol.vue")['default']
    'LazyUiBtnPrimary': typeof import("../components/ui/btnPrimary/BtnPrimary.vue")['default']
    'LazyUiBtnSecondary': typeof import("../components/ui/btnSecondary/BtnSecondary.vue")['default']
    'LazyUiHeader': typeof import("../components/ui/header/Header.vue")['default']
    'LazyUiLoader': typeof import("../components/ui/loader/Loader.vue")['default']
    'LazyUiPlatformCircle': typeof import("../components/ui/platformCircle/PlatformCircle.vue")['default']
    'LazyUiPlatformTag': typeof import("../components/ui/platformTag/PlatformTag.vue")['default']
    'LazyUiPlatformsList': typeof import("../components/ui/platformsList/PlatformsList.vue")['default']
    'LazyUiPosterCard': typeof import("../components/ui/posterCard/PosterCard.vue")['default']
    'LazyUiPostersList': typeof import("../components/ui/postersList/PostersList.vue")['default']
    'LazyUiSearchBar': typeof import("../components/ui/searchBar/SearchBar.vue")['default']
    'LazyUiSlider': typeof import("../components/ui/slider/Slider.vue")['default']
    'LazyUiTag': typeof import("../components/ui/tag/Tag.vue")['default']
    'LazyUiTrailersList': typeof import("../components/ui/trailersList/TrailersList.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyVueCarousel': typeof import("vue3-carousel/dist/carousel")['Carousel']
    'LazyVueSlide': typeof import("vue3-carousel/dist/carousel")['Slide']
    'LazyVuePagination': typeof import("vue3-carousel/dist/carousel")['Pagination']
    'LazyVueNavigation': typeof import("vue3-carousel/dist/carousel")['Navigation']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const UiActorCol: typeof import("../components/ui/actorCol/ActorCol.vue")['default']
export const UiBtnPrimary: typeof import("../components/ui/btnPrimary/BtnPrimary.vue")['default']
export const UiBtnSecondary: typeof import("../components/ui/btnSecondary/BtnSecondary.vue")['default']
export const UiHeader: typeof import("../components/ui/header/Header.vue")['default']
export const UiLoader: typeof import("../components/ui/loader/Loader.vue")['default']
export const UiPlatformCircle: typeof import("../components/ui/platformCircle/PlatformCircle.vue")['default']
export const UiPlatformTag: typeof import("../components/ui/platformTag/PlatformTag.vue")['default']
export const UiPlatformsList: typeof import("../components/ui/platformsList/PlatformsList.vue")['default']
export const UiPosterCard: typeof import("../components/ui/posterCard/PosterCard.vue")['default']
export const UiPostersList: typeof import("../components/ui/postersList/PostersList.vue")['default']
export const UiSearchBar: typeof import("../components/ui/searchBar/SearchBar.vue")['default']
export const UiSlider: typeof import("../components/ui/slider/Slider.vue")['default']
export const UiTag: typeof import("../components/ui/tag/Tag.vue")['default']
export const UiTrailersList: typeof import("../components/ui/trailersList/TrailersList.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VueCarousel: typeof import("vue3-carousel/dist/carousel")['Carousel']
export const VueSlide: typeof import("vue3-carousel/dist/carousel")['Slide']
export const VuePagination: typeof import("vue3-carousel/dist/carousel")['Pagination']
export const VueNavigation: typeof import("vue3-carousel/dist/carousel")['Navigation']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyUiActorCol: typeof import("../components/ui/actorCol/ActorCol.vue")['default']
export const LazyUiBtnPrimary: typeof import("../components/ui/btnPrimary/BtnPrimary.vue")['default']
export const LazyUiBtnSecondary: typeof import("../components/ui/btnSecondary/BtnSecondary.vue")['default']
export const LazyUiHeader: typeof import("../components/ui/header/Header.vue")['default']
export const LazyUiLoader: typeof import("../components/ui/loader/Loader.vue")['default']
export const LazyUiPlatformCircle: typeof import("../components/ui/platformCircle/PlatformCircle.vue")['default']
export const LazyUiPlatformTag: typeof import("../components/ui/platformTag/PlatformTag.vue")['default']
export const LazyUiPlatformsList: typeof import("../components/ui/platformsList/PlatformsList.vue")['default']
export const LazyUiPosterCard: typeof import("../components/ui/posterCard/PosterCard.vue")['default']
export const LazyUiPostersList: typeof import("../components/ui/postersList/PostersList.vue")['default']
export const LazyUiSearchBar: typeof import("../components/ui/searchBar/SearchBar.vue")['default']
export const LazyUiSlider: typeof import("../components/ui/slider/Slider.vue")['default']
export const LazyUiTag: typeof import("../components/ui/tag/Tag.vue")['default']
export const LazyUiTrailersList: typeof import("../components/ui/trailersList/TrailersList.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyVueCarousel: typeof import("vue3-carousel/dist/carousel")['Carousel']
export const LazyVueSlide: typeof import("vue3-carousel/dist/carousel")['Slide']
export const LazyVuePagination: typeof import("vue3-carousel/dist/carousel")['Pagination']
export const LazyVueNavigation: typeof import("vue3-carousel/dist/carousel")['Navigation']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
